//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilletWCFClient.BilletReferenceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BilletWCFService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BilletReferenceService.IBilletService")]
    public interface IBilletService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisMCMedBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisMCMedBrobizzResponse")]
        int GetPrisMCMedBrobizz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisMCMedBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisMCMedBrobizzResponse")]
        System.Threading.Tasks.Task<int> GetPrisMCMedBrobizzAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisMCUBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisMCUBrobizzResponse")]
        int GetPrisMCUBrobizz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisMCUBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisMCUBrobizzResponse")]
        System.Threading.Tasks.Task<int> GetPrisMCUBrobizzAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisBilMedBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisBilMedBrobizzResponse")]
        int GetPrisBilMedBrobizz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisBilMedBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisBilMedBrobizzResponse")]
        System.Threading.Tasks.Task<int> GetPrisBilMedBrobizzAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisBilUBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisBilUBrobizzResponse")]
        int GetPrisBilUBrobizz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetPrisBilUBrobizz", ReplyAction="http://tempuri.org/IBilletService/GetPrisBilUBrobizzResponse")]
        System.Threading.Tasks.Task<int> GetPrisBilUBrobizzAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBilletService/GetDataUsingDataContractResponse")]
        BilletWCFClient.BilletReferenceService.CompositeType GetDataUsingDataContract(BilletWCFClient.BilletReferenceService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBilletService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBilletService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BilletWCFClient.BilletReferenceService.CompositeType> GetDataUsingDataContractAsync(BilletWCFClient.BilletReferenceService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBilletServiceChannel : BilletWCFClient.BilletReferenceService.IBilletService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BilletServiceClient : System.ServiceModel.ClientBase<BilletWCFClient.BilletReferenceService.IBilletService>, BilletWCFClient.BilletReferenceService.IBilletService {
        
        public BilletServiceClient() {
        }
        
        public BilletServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BilletServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilletServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilletServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetPrisMCMedBrobizz() {
            return base.Channel.GetPrisMCMedBrobizz();
        }
        
        public System.Threading.Tasks.Task<int> GetPrisMCMedBrobizzAsync() {
            return base.Channel.GetPrisMCMedBrobizzAsync();
        }
        
        public int GetPrisMCUBrobizz() {
            return base.Channel.GetPrisMCUBrobizz();
        }
        
        public System.Threading.Tasks.Task<int> GetPrisMCUBrobizzAsync() {
            return base.Channel.GetPrisMCUBrobizzAsync();
        }
        
        public int GetPrisBilMedBrobizz() {
            return base.Channel.GetPrisBilMedBrobizz();
        }
        
        public System.Threading.Tasks.Task<int> GetPrisBilMedBrobizzAsync() {
            return base.Channel.GetPrisBilMedBrobizzAsync();
        }
        
        public int GetPrisBilUBrobizz() {
            return base.Channel.GetPrisBilUBrobizz();
        }
        
        public System.Threading.Tasks.Task<int> GetPrisBilUBrobizzAsync() {
            return base.Channel.GetPrisBilUBrobizzAsync();
        }
        
        public BilletWCFClient.BilletReferenceService.CompositeType GetDataUsingDataContract(BilletWCFClient.BilletReferenceService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BilletWCFClient.BilletReferenceService.CompositeType> GetDataUsingDataContractAsync(BilletWCFClient.BilletReferenceService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
